[package]
org = "codeCrew"
name = "online_election"
version = "0.1.0"
distribution = "2201.12.2"

[build-options]
observabilityIncluded = true
[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.6.0"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"


